/*
* BSD 3-Clause License
* Copyright © 2020. TIBCO Software Inc.
* This file is subject to the license terms contained
* in the license file that is distributed with this file.
 */
package tcitoprommetrics

import (
	"testing"

	"github.com/project-flogo/core/data/mapper"
	"github.com/project-flogo/core/data/resolve"
	"github.com/project-flogo/core/support/test"
	"github.com/stretchr/testify/assert"
)

func TestPromMetrics(t *testing.T) {

	var a []AutoGenerated

	var b AutoGenerated

	b.App.AppName = "test"
	b.App.AppType = "flogo"
	b.App.AppID = "id1"

	var c AppInstanceMetrics

	c.AppInstanceMetrics.AppName = "test"
	c.AppInstanceMetrics.AppVersion = "1.0"

	var d Flows

	d.Completed = 1
	d.Failed = 0
	d.Started = 1
	d.AvgExecTime = 1.1
	d.MaxExecTime = 1.2
	d.MinExecTime = 1.0

	//	kkk := []byte(`{\"tci_app_executions\":[{\"labels\":{\"status\":\"success\"},\"value\":2},{\"labels\":{\"status\":\"failure\"},\"value\":0}],\"tci_app_instances_cpu\":[{\"labels\":{\"status\":\"max\"},\"value\":2.4000000953674316},{\"labels\":{\"status\":\"min\"},\"value\":0},{\"labels\":{\"status\":\"avg\"},\"value\":0.15750000238832512}],\"tci_app_instances_memory\":[{\"labels\":{\"status\":\"max\"},\"value\":27},{\"labels\":{\"status\":\"min\"},\"value\":26.450000762939453},{\"labels\":{\"status\":\"avg\"},\"value\":26.72612153159244}]}`)
	//	newValue := AppMetrics{}
	//	err := json.Unmarshal(kkk, &newValue)
	//	println(newValue.TciAppExecutions[0].Value)

	c.AppInstanceMetrics.Flows = append(c.AppInstanceMetrics.Flows, d)

	b.AppInstanceMetrics = append(b.AppInstanceMetrics, c)

	a = append(a, b)

	mf := mapper.NewFactory(resolve.GetBasicResolver())
	iCtx := test.NewActivityInitContext(nil, mf)
	act, err := New(iCtx)
	assert.Nil(t, err)

	tc := test.NewActivityContext(act.Metadata())

	input := &Input{
		Metrics: a,
	}
	tc.SetInputObject(input)

	act.Eval(tc)

	output := &Output{}
	tc.GetOutputObject(output)
	assert.NotEmpty(t, output.Data)

	println(output.Data)

}
